// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg8EjzRsdiSB2VRkmsrM-Ep3JxJX9QpIs',
    appId: '1:360105152580:web:fe85c5bc0a25d9de0eec11',
    messagingSenderId: '360105152580',
    projectId: 'flutterquiz-kg',
    authDomain: 'flutterquiz-kg.firebaseapp.com',
    storageBucket: 'flutterquiz-kg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhd_hpDkHLPImd2wiq8VLsc5g_o0OAYmc',
    appId: '1:360105152580:android:414b0b1678b07a640eec11',
    messagingSenderId: '360105152580',
    projectId: 'flutterquiz-kg',
    storageBucket: 'flutterquiz-kg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe80hoo8sCsrMo5unnYrxelh-Fs3xBjmQ',
    appId: '1:360105152580:ios:7700cfb1b644740b0eec11',
    messagingSenderId: '360105152580',
    projectId: 'flutterquiz-kg',
    storageBucket: 'flutterquiz-kg.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe80hoo8sCsrMo5unnYrxelh-Fs3xBjmQ',
    appId: '1:360105152580:ios:7700cfb1b644740b0eec11',
    messagingSenderId: '360105152580',
    projectId: 'flutterquiz-kg',
    storageBucket: 'flutterquiz-kg.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg8EjzRsdiSB2VRkmsrM-Ep3JxJX9QpIs',
    appId: '1:360105152580:web:4f851f371ea531370eec11',
    messagingSenderId: '360105152580',
    projectId: 'flutterquiz-kg',
    authDomain: 'flutterquiz-kg.firebaseapp.com',
    storageBucket: 'flutterquiz-kg.firebasestorage.app',
  );
}
